const stockOptions2 = [
    { label: "Apple Inc.", value: "AAPL" },
    { label: "NVIDIA Corporation", value: "NVDA" },
    { label: "Microsoft Corporation", value: "MSFT" },
    { label: "Alphabet Inc.", value: "GOOG" },
    { label: "Alphabet Inc.", value: "GOOGL" },
    { label: "Amazon.com, Inc.", value: "AMZN" },
    { label: "Meta Platforms, Inc.", value: "META" },
    { label: "Berkshire Hathaway Inc.", value: "BRK.B" },
    { label: "Broadcom Inc.", value: "AVGO" },
    { label: "Eli Lilly and Company", value: "LLY" },
    { label: "Tesla, Inc.", value: "TSLA" },
    { label: "Walmart Inc.", value: "WMT" },
    { label: "JPMorgan Chase & Co.", value: "JPM" },
    { label: "Visa Inc.", value: "V" },
    { label: "Exxon Mobil Corporation", value: "XOM" },
    { label: "UnitedHealth Group Incorporated", value: "UNH" },
    { label: "Oracle Corporation", value: "ORCL" },
    { label: "Mastercard Incorporated", value: "MA" },
    { label: "The Home Depot, Inc.", value: "HD" },
    { label: "The Procter & Gamble Company", value: "PG" },
    { label: "Costco Wholesale Corporation", value: "COST" },
    { label: "Johnson & Johnson", value: "JNJ" },
    { label: "Netflix, Inc.", value: "NFLX" },
    { label: "AbbVie Inc.", value: "ABBV" },
    { label: "Bank of America Corporation", value: "BAC" },
    { label: "The Coca-Cola Company", value: "KO" },
    { label: "Salesforce, Inc.", value: "CRM" },
    { label: "Chevron Corporation", value: "CVX" },
    { label: "Merck & Co., Inc.", value: "MRK" },
    { label: "T-Mobile US, Inc.", value: "TMUS" },
    { label: "Advanced Micro Devices, Inc.", value: "AMD" },
    { label: "PepsiCo, Inc.", value: "PEP" },
    { label: "Accenture plc", value: "ACN" },
    { label: "Linde plc", value: "LIN" },
    { label: "Thermo Fisher Scientific Inc.", value: "TMO" },
    { label: "McDonald's Corporation", value: "MCD" },
    { label: "Cisco Systems, Inc.", value: "CSCO" },
    { label: "Adobe Inc.", value: "ADBE" },
    { label: "Wells Fargo & Company", value: "WFC" },
    { label: "International Business Machines Corporation", value: "IBM" },
];

export default stockOptions2;